include $(GOROOT)/src/Make.inc

TARG=basicsound

CGOFILES=basicsound_darwin.go
CGO_OFILES=lib_darwin.o
CGO_LDFLAGS=-framework Cocoa

include $(GOROOT)/src/Make.pkg

%.o : %.m
	$(HOST_CC) -c -o $@ $<

% : install %.go
	$(GC) $*.go
	$(LD) -o $@ $*.$O
